spring:
  datasource:
    type: com.mysql.cj.jdbc.MysqlDataSource
    url: jdbc:mysql://localhost:3306/quartz
    username: root
    password: test
  quartz:
    scheduler-name: api-quartz
    job-store-type: jdbc
    jdbc:
      initialize-schema: always